# Generated by Django 4.1.7 on 2023-04-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_events_contract_address_alter_events_abi_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="contract_address",
            field=models.TextField(default="False"),
        ),
    ]
