# Generated by Django 4.1.7 on 2023-04-11 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_alter_events_contract_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="events",
            name="contract_address",
        ),
    ]
