# Generated by Django 4.1.7 on 2023-04-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_events_contract_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="image_path",
            field=models.ImageField(null=True, upload_to="static/images"),
        ),
    ]
