# Generated by Django 4.1.7 on 2023-04-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_events_image_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="event_nft",
            field=models.TextField(default="False"),
        ),
    ]
