# Generated by Django 4.1.7 on 2023-04-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=30)),
                ("event_description", models.CharField(max_length=100)),
                ("max_tickets", models.TextField()),
                ("start_date", models.CharField(max_length=13)),
                ("end_date", models.CharField(max_length=13)),
                ("event_created", models.DateTimeField(auto_now_add=True)),
                ("account_id", models.CharField(max_length=45)),
            ],
        ),
    ]
