# Generated by Django 4.1.7 on 2023-04-01 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Events",
        ),
    ]
