# Generated by Django 4.1.7 on 2023-04-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_events_abi_events_contract_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="abi",
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name="events",
            name="contract_hash",
            field=models.TextField(default=False),
        ),
    ]
