# Generated by Django 4.1.7 on 2023-04-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_remove_events_contract_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="contract_address",
            field=models.TextField(default="False"),
        ),
    ]
